### ISSUE TITLE
(...).hcOffcanvasNav is not a function after Upgrade to 5.0.3 

### ISSUE THREAD

**Issue by glavrjk** [somewebmedia/hc-offcanvas-nav#43]
Hello i have a issue after update to 5.0.3 from webpack. (...).hcOffcanvasNav  is not a function but it was working without problems before. There is something wrong in my app.js file? or did the alias change after update? I had to rollback to 4.2.6 meanwhile, i'll appreciate your help.

```
import $ from 'jquery';
import 'bootstrap';
import 'hc-offcanvas-nav';

$(function () {
        $('#main-nav').hcOffcanvasNav({
                disableAt: false,
                customToggle: $('.toggle'),
                levelSpacing: 40,
                navTitle: 'MENÚ PRINCIPAL',
                labelClose: 'Cerrar',
                labelBack: 'Atrás',
                levelTitles: true,
                levelTitleAsBack: true,
                pushContent: '#container',
                insertClose: 2
        });
});
```

**Comment by somewebmedia** [comment]
Hey @glavrjk, in the major version `5` the lib is now dependency free, so you don't need jQuery anymore for using it, but it can still be used with it if you prefer that way (check the readme).

In order to use it as jQuery plugin, the jQuery object needs to be attached to the global window object, which is not the case if you load it with Webpack or Browserify.
Read it here: https://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack

But to save yourself the hassle just instance it like this:

```
const Nav = new hcOffcanvasNav('#main-nav', {
    disableAt: false,
    customToggle: $('.toggle'),
    levelSpacing: 40,
    navTitle: 'MENÚ PRINCIPAL',
    labelClose: 'Cerrar',
    labelBack: 'Atrás',
    levelTitles: true,
    levelTitleAsBack: true,
    pushContent: '#container',
    insertClose: 2
});
```

**Comment by somewebmedia** [comment]
Just update to new `v5.0.4` I just published, I actually forgot to return the main function. :)

**Comment by glavrjk** [comment]
> ggle: $('.toggle'),

I'ts still not working man. I'm using the symfony's webpack. I took your recommendation and i deleted the $ import and it's fine but the library broken with same issue. this my complete app.js

```
/*
 * Welcome to your app's main JavaScript file!
 *
 * We recommend including the built version of this JavaScript file
 * (and its CSS file) in your base layout (base.html.twig).
 */

// any CSS you import will output into a single css file (app.css in this case)
import '../css/app.css';
// Need jQuery? Install it with "yarn add jquery", then uncomment to import it.
// import $ from 'jquery';
import 'bootstrap';
import 'noty';
import * as hcOffcanvasNav  from 'hc-offcanvas-nav';

$.isMobile = (function () {
    var userAgent = navigator.userAgent.toLowerCase();
    if (userAgent.match(/android/i)) {
        return 'android';
    } else if (userAgent.match(/webos/i)) {
        return 'webos';
    } else if (userAgent.match(/iphone/i)) {
        return 'iphone';
    } else if (userAgent.match(/ipad/i)) {
        return 'ipad';
    } else if (userAgent.match(/ipod/i)) {
        return 'ipod';
    } else if (userAgent.match(/blackberry/i)) {
        return 'blackberry';
    } else if (userAgent.match(/windows phone/i)) {
        return 'winphone';
    }
    return false;
})();
// =========== Notification Plugin ============
window.showNotification = function (type, text) {
    const Noty = require('noty');
    new Noty({
        theme: 'metroui',
        layout: 'bottomRight',
        progressBar: true,
        timeout: 1500,
        type: type,
        text: text
    }).show();
};
// ===========Cart Trigger============
window.refreshCart = function (type, element, max) {
    if ($('#' + type + '-' + element).val() <= max) {
        $('#' + type + '-form' + '-' + element).submit();
    }
};
$(function () {
// ===========Right Sidebar============
    $('[data-toggle="offcanvas"]').on('click', function () {
        $('body').toggleClass('toggled');
    });
    // ===========Hover Nav============ 
    $('.navbar-nav li.dropdown').on('mouseenter', function () {
        $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeIn(500);
    });
    $('.navbar-nav li.dropdown').on('mouseleave', function () {
        $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeOut(500);
    });
    // ===========Tooltip============
    $('[data-toggle="tooltip"]').tooltip();
    // ===========Mobile Menu============
    $('#main-nav').hcOffcanvasNav({
        disableAt: false,
        customToggle: $('.toggle'),
        levelSpacing: 40,
        navTitle: 'MENÚ PRINCIPAL',
        labelClose: 'Cerrar',
        labelBack: 'Atrás',
        levelTitles: true,
        levelTitleAsBack: true,
        pushContent: '#container',
        insertClose: 2
    });
});

// ============== Service Worker ==============
// Nos aseguramos que el navegador implementa la api 'serviceWorker'
if ('serviceWorker' in navigator) {
// Esperamos al evento load para registrar nuestro service worker
    window.addEventListener('load', () => {
// Registramos el service worker
        navigator.serviceWorker.register('/webpushr-sw.js');
    });
}

//     start webpushr code 
const data = JSON.parse(document.getElementById('body').getAttribute('fetch-data'));
if (data) {
    (function (w, d, s, id) {
        if (typeof (w.webpushr) !== 'undefined') {
            console.log(w.webpushr);
            return;
        }
        w.webpushr = w.webpushr || function () {
            (w.webpushr.q = w.webpushr.q || []).push(arguments)
        };
        var js, fjs = d.getElementsByTagName(s)[0];
        js = d.createElement(s);
        js.id = id;
        js.src = "https://cdn.webpushr.com/app.min.js";
        fjs.parentNode.appendChild(js);
    }(window, document, 'script', 'webpushr-jssdk'));
    webpushr('setup', {'key': 'BA6HB0x6O26jEMp_EZIdvNP3OZaLmzsvvOZ5M97SZFHn7ornJJnwm4HAW_RaC3tw7CstAJXD1sjoTCXPYjFIrl0'});
    var attr = {
        'email': data.email,
        'rif': data.rif,
        'description': data.description,
        'phone': data.phone,
        'external_id': data.id
    };
    webpushr('attributes', attr);
    webpushr('fetch_id', function (sid) {
        if (sid !== data.fetch) {
            $.ajax({
                type: 'POST',
                url: '/fetch',
                data: {fetch_id: sid},
                dataType: 'json'
            }).done(function (resp) {
                console.log(resp);
            }).fail(function (resp) {
                console.error('xhr failed', resp);
                showNotification('danger', resp);
                return false;
            });
            console.log('webpushr subscriber id: ' + sid);
        }
    });
}
// end webpushr code 

```

**Comment by somewebmedia** [comment]
Can you try this code:

```
// any CSS you import will output into a single css file (app.css in this case)
import '../css/app.css';
// Need jQuery? Install it with "yarn add jquery", then uncomment to import it.
import $ from 'jquery';
import 'bootstrap';
import 'noty';
import hcOffcanvasNav from 'hc-offcanvas-nav';

$(function () {
// ===========Right Sidebar============
    $('[data-toggle="offcanvas"]').on('click', function () {
        $('body').toggleClass('toggled');
    });
    // ===========Hover Nav============ 
    $('.navbar-nav li.dropdown').on('mouseenter', function () {
        $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeIn(500);
    });
    $('.navbar-nav li.dropdown').on('mouseleave', function () {
        $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeOut(500);
    });
    // ===========Tooltip============
    $('[data-toggle="tooltip"]').tooltip();
    // ===========Mobile Menu============
    new hcOffcanvasNav('#main-nav', {
        disableAt: false,
        customToggle: $('.toggle'),
        levelSpacing: 40,
        navTitle: 'MENÚ PRINCIPAL',
        labelClose: 'Cerrar',
        labelBack: 'Atrás',
        levelTitles: true,
        levelTitleAsBack: true,
        pushContent: '#container',
        insertClose: 2
    });
});
```

**Comment by somewebmedia** [comment]
@glavrjk did you manage to get it to work?

**Comment by glavrjk** [comment]
> @glavrjk did you manage to get it to work?

thank you so much you solution worked for me...! 
Sorry for the delay

**Comment by somewebmedia** [comment]
No problem, glad I could help.
